name: mt_adaptation_dev
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9.*
  - pip
  - numpy=1.19.*
  - pytorch=1.9.*
  - scipy=1.5.*
  - tqdm
  - pip:
      - more-itertools
      - torchtyping